# Generated by Django 4.2.3 on 2024-07-22 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsignature.fields
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(blank=True, max_length=500, null=True)),
                ('todo_date', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=120)),
                ('supply_date', models.DateField(verbose_name=datetime.date.today)),
                ('model', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('asset_department', models.CharField(max_length=50)),
                ('present_condition', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('owner', models.IntegerField(default=1)),
                ('asset_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('received_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.IntegerField(blank=True, default='0', null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('manager', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=45, verbose_name='Department name')),
                ('appendage_name', models.CharField(default='None', max_length=40, verbose_name='Appendage')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('model', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('activities', models.TextField(default='', max_length=300)),
                ('last_service', models.DateTimeField(blank=True, default='', null=True)),
                ('next_service', models.DateTimeField(blank=True, default='', null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, verbose_name='First name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last name')),
                ('dept', models.CharField(max_length=45, verbose_name='department')),
            ],
        ),
        migrations.CreateModel(
            name='MaintOfficers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, verbose_name='First name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=500, null=True)),
                ('department1', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', jsignature.fields.JSignatureField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=500, null=True)),
                ('section', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Supplier name')),
                ('address', models.CharField(max_length=250)),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Zip code')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone no')),
                ('web', models.URLField(blank=True, verbose_name='Website Address')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('owner', models.IntegerField(default=1)),
                ('venue_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_unit', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('receiving_unit', models.CharField(max_length=50)),
                ('date_received', models.DateField(verbose_name=datetime.date.today)),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('machine', models.CharField(default='', max_length=250)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('attendees', models.ManyToManyField(blank=True, to='myapp.maintofficers')),
                ('item_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.consumable')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDoneList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDoneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('name', models.TextField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=myapp.models.one_week_hence)),
                ('cost', models.CharField(max_length=150)),
                ('work_list', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.workdonelist')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=myapp.models.one_week_hence)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emanating_dept', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('requesting_officer', models.TextField(blank=True, max_length=500, null=True, verbose_name='In_Charge')),
                ('hod_consent', models.CharField(max_length=30)),
                ('action_by', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('request_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.equipment')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.manager')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.section')),
                ('sub_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.sub_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Mech_Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='attendees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.maintofficers'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department'),
        ),
    ]
